# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 20:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('start_time', models.CharField(max_length=200)),
                ('end_time', models.CharField(max_length=200)),
                ('discription', models.TextField()),
                ('poster1', models.CharField(blank=True, default='', max_length=400)),
                ('poster2', models.CharField(blank=True, default='', max_length=400)),
                ('poster3', models.CharField(blank=True, default='', max_length=400)),
                ('poster4', models.CharField(blank=True, default='', max_length=400)),
                ('video1', models.CharField(blank=True, default='', max_length=400)),
                ('video2', models.CharField(blank=True, default='', max_length=400)),
                ('person_name_1', models.CharField(max_length=200)),
                ('person_contact_1', models.CharField(max_length=200)),
                ('person_name_2', models.CharField(max_length=200)),
                ('person_contact_2', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2017, 6, 16, 20, 32, 50, 99623, tzinfo=utc))),
            ],
        ),
    ]
