# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 21:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='poster1',
            new_name='addBanner1',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='poster2',
            new_name='addBanner2',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='poster3',
            new_name='addBanner3',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='poster4',
            new_name='addBanner5',
        ),
        migrations.AlterField(
            model_name='events',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 24, 21, 26, 59, 391273, tzinfo=utc)),
        ),
    ]
