# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 21:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20170624_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='addBanner5',
            new_name='addBanner4',
        ),
        migrations.AlterField(
            model_name='events',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 24, 21, 32, 34, 590188, tzinfo=utc)),
        ),
    ]
