# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clubName', models.CharField(max_length=200)),
                ('clubUserUrl', models.CharField(max_length=200)),
                ('clubLogo', models.CharField(max_length=200)),
                ('clubAdmin', models.CharField(max_length=200)),
            ],
        ),
    ]
